### ISSUE TITLE
Issue in deserialization

### ISSUE THREAD

**Issue by FayazRahman** [sonarosa/prapro#1]
```
r2 = np.frombuffer(random_bytes, dtype=random_array.dtype)
r2 = r2.reshape(random_array.shape)  
```

Assuming `random_array` object does not exist when you are recreating `r2` will be better. Store  `dtype` and `shape` separately.

**Comment by sonarosa** [comment]
`random_dtype = random_array.dtype

random_shape = random_array.shape

random_bytes = random_array.tobytes()
`
