### ISSUE TITLE
Add better test

### ISSUE THREAD

**Issue by FayazRahman** [sonarosa/prapro#2]
```
tolerance = 1e-6  
are_equal = np.allclose(random_array, r2, atol=tolerance)
```

Arrays should be equal with zero tolerance. Use `np.testing.assert_array_equal` for testing or `np.array_equal`.

**Comment by sonarosa** [comment]
`np.testing.assert_array_equal(random_array, r2)` is this okay?

**Comment by FayazRahman** [comment]
👍
